sudo: required
dist: trusty
language: node_js
node_js:
  - 0.12
  - 4
  - 6
env:
  - TARGET=test-coverage
  - TARGET=test-browser
script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run travis-$TARGET
